{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "0b855dd2",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "import pandas as pd\n",
    "from sklearn.model_selection import cross_val_score\n",
    "from sklearn import svm\n",
    "from sklearn.preprocessing import LabelEncoder\n",
    "from sklearn.pipeline import Pipeline\n",
    "from sklearn.decomposition import PCA\n",
    "from sklearn.feature_selection import SelectKBest, chi2\n",
    "from sklearn.linear_model import ElasticNet\n",
    "from sklearn.neighbors import KNeighborsClassifier\n",
    "from sklearn.ensemble import GradientBoostingClassifier\n",
    "from pathlib import Path"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "049372a7",
   "metadata": {},
   "outputs": [],
   "source": [
    "DATA_PATH=\"/Users/zubrikhina/Documents/datasets/EEG_baseline_with_markers/all_data_features\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "c5afdf09",
   "metadata": {},
   "outputs": [],
   "source": [
    "DATA_PATH='/Users/zubrikhina/Documents/datasets/eeg_novossibirsk_preproc'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "3014cfee",
   "metadata": {},
   "outputs": [],
   "source": [
    "def build_models_feature_selection(X,y):    \n",
    "    models = {\n",
    "        'fs_lr_l1': Pipeline([('feature_selection',SelectKBest(chi2, k=50)), \n",
    "              ('lg', LogisticRegression(penalty='l1',solver='liblinear', C =1))]),\n",
    "\n",
    "        'fs_lr_l2': Pipeline([('feature_selection', SelectKBest(chi2, k=50)), \n",
    "              ('lg', LogisticRegression(penalty='l2',solver='liblinear',C =1))]),\n",
    "        'fs_rf_7': Pipeline([('feature_selection', SelectKBest(chi2, k=50)), \n",
    "              ('lg', RandomForestClassifier(n_estimators=100, max_depth=7))]),\n",
    "        'fs_rf_5':Pipeline([('feature_selection', SelectKBest(chi2, k=50)), \n",
    "              ('lg', RandomForestClassifier(n_estimators=100, max_depth=5))]),\n",
    "        'fs_svm_stand': Pipeline([('feature_selection', SelectKBest(chi2, k=50)), \n",
    "              ('lg', svm.SVC(C=0.1))]),\n",
    "\n",
    "        'fs_knn':Pipeline([('feature_selection', SelectKBest(chi2, k=50)), \n",
    "              ('lg', KNeighborsClassifier(n_neighbors=5))]),\n",
    "        'fs_gb': Pipeline([('feature_selection', SelectKBest(chi2, k=50)), \n",
    "              ('lg', GradientBoostingClassifier(max_depth=5))]),\n",
    "        }\n",
    "    for name, model in models.items():\n",
    "        try:\n",
    "            scores = cross_val_score(model, X, y, cv=10, scoring='roc_auc')\n",
    "            print(name, f\"{scores.mean():.3f}+/-{scores.std():.3f}\")\n",
    "        except Exception as e:\n",
    "            print(e)\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "b2a12840",
   "metadata": {},
   "outputs": [],
   "source": [
    "def build_models_pca(X,y):    \n",
    "    models = {\n",
    "        'pca_lr_l1': Pipeline([('pca', PCA(n_components=50)), \n",
    "              ('lg', LogisticRegression(penalty='l1',solver='liblinear', C =1))]),\n",
    "\n",
    "        'pca_lr_l2': Pipeline([('pca', PCA(n_components=50)), \n",
    "              ('lg', LogisticRegression(penalty='l2',solver='liblinear',C =1))]),\n",
    "        'pca_rf_7': Pipeline([('pca', PCA(n_components=50)), \n",
    "              ('lg', RandomForestClassifier(n_estimators=100, max_depth=7))]),\n",
    "        'pca_rf_5':Pipeline([('pca', PCA(n_components=50)), \n",
    "              ('lg', RandomForestClassifier(n_estimators=100, max_depth=5))]),\n",
    "        'pca_svm_stand': Pipeline([('pca', PCA(n_components=60)), \n",
    "              ('lg', svm.SVC(C=0.1))]),\n",
    "        'pca_knn': Pipeline([('pca', PCA(n_components=50)), \n",
    "              ('knn', KNeighborsClassifier(n_neighbors=5))]),\n",
    "        'pca_gb': Pipeline([('pca', PCA(n_components=50)), \n",
    "              ('gb', GradientBoostingClassifier(max_depth=5))]),\n",
    "    }\n",
    "    for name, model in models.items():\n",
    "        scores = cross_val_score(model, X, y, cv=10, scoring='roc_auc')\n",
    "        print(name, f\"{scores.mean():.3f}+/-{scores.std():.3f}\")\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "3ed8a010",
   "metadata": {},
   "outputs": [],
   "source": [
    "def build_models(X,y):    \n",
    "    models = {\n",
    "        'lr_l1': LogisticRegression(penalty='l1',solver='liblinear',C =1),\n",
    "        'lr_l2': LogisticRegression(penalty='l2',solver='liblinear',C =1),\n",
    "        'rf_7': RandomForestClassifier(n_estimators=100, max_depth=7),\n",
    "        'rf_5': RandomForestClassifier(n_estimators=100, max_depth=5),\n",
    "        'svm_stand_0.1': svm.SVC(C=0.1),\n",
    "        'svm_stand_0.01': svm.SVC(C=0.01),\n",
    "        'knn': KNeighborsClassifier(n_neighbors=10),\n",
    "        'gb': GradientBoostingClassifier(max_depth=5)\n",
    "    }\n",
    "    for name, model in models.items():\n",
    "        scores = cross_val_score(model, X, y, cv=10, scoring='f1')\n",
    "        print(name, f\"{scores.mean():.3f}+/-{scores.std():.3f}\")\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "555ec41d",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "bands.csv\n",
      "lr_l1 0.582+/-0.319\n",
      "lr_l2 0.692+/-0.204\n",
      "rf_7 0.715+/-0.190\n",
      "rf_5 0.659+/-0.279\n",
      "svm_stand_0.1 0.148+/-0.196\n",
      "svm_stand_0.01 0.000+/-0.000\n",
      "knn 0.519+/-0.232\n",
      "gb 0.606+/-0.147\n",
      "_______________\n",
      "env.csv\n",
      "lr_l1 0.574+/-0.111\n",
      "lr_l2 0.626+/-0.143\n",
      "rf_7 0.518+/-0.171\n",
      "rf_5 0.538+/-0.182\n",
      "svm_stand_0.1 0.000+/-0.000\n",
      "svm_stand_0.01 0.000+/-0.000\n",
      "knn 0.539+/-0.154\n",
      "gb 0.539+/-0.168\n",
      "_______________\n",
      "env_theta.csv\n",
      "lr_l1 0.628+/-0.183\n",
      "lr_l2 0.591+/-0.251\n",
      "rf_7 0.619+/-0.169\n",
      "rf_5 0.627+/-0.072\n",
      "svm_stand_0.1 0.000+/-0.000\n",
      "svm_stand_0.01 0.000+/-0.000\n",
      "knn 0.336+/-0.221\n",
      "gb 0.492+/-0.135\n",
      "_______________\n"
     ]
    }
   ],
   "source": [
    "for path in Path(DATA_PATH).iterdir():\n",
    "    print(path.name)\n",
    "    data =pd.read_csv(path)\n",
    "    data =data.fillna(0)\n",
    "    data =data.sample(frac=1).reset_index(drop =True)\n",
    "    mdd =data.loc[data['target']==1]\n",
    "    health =data.loc[data['target']==0][:50]\n",
    "    data =pd.concat([mdd,health])\n",
    "    data=data.reset_index(drop =True)\n",
    "    y=data['target']\n",
    "    X=data.drop(columns=['fn', 'target'])\n",
    "    build_models(X,y)\n",
    "    print(\"_______________\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "f44ed5e7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "bands.csv\n",
      "pca_lr_l1 0.776+/-0.168\n",
      "pca_lr_l2 0.756+/-0.157\n",
      "pca_rf_7 0.680+/-0.212\n",
      "pca_rf_5 0.734+/-0.223\n",
      "pca_svm_stand 0.717+/-0.137\n",
      "pca_knn 0.648+/-0.171\n",
      "pca_gb 0.534+/-0.199\n",
      "_______________\n",
      "env.csv\n",
      "pca_lr_l1 0.718+/-0.158\n",
      "pca_lr_l2 0.729+/-0.170\n",
      "pca_rf_7 0.717+/-0.099\n",
      "pca_rf_5 0.816+/-0.127\n",
      "pca_svm_stand 0.668+/-0.154\n",
      "pca_knn 0.656+/-0.178\n",
      "pca_gb 0.592+/-0.168\n",
      "_______________\n",
      "env_theta.csv\n",
      "pca_lr_l1 0.635+/-0.166\n",
      "pca_lr_l2 0.656+/-0.207\n",
      "pca_rf_7 0.711+/-0.192\n",
      "pca_rf_5 0.727+/-0.131\n",
      "pca_svm_stand 0.621+/-0.207\n",
      "pca_knn 0.584+/-0.212\n",
      "pca_gb 0.644+/-0.125\n",
      "_______________\n"
     ]
    }
   ],
   "source": [
    "for path in Path(DATA_PATH).iterdir():\n",
    "    print(path.name)\n",
    "    data =pd.read_csv(path)\n",
    "    data =data.fillna(0)\n",
    "    data =data.sample(frac=1).reset_index(drop =True)\n",
    "    mdd =data.loc[data['target']==1]\n",
    "    health =data.loc[data['target']==0][:50]\n",
    "    data =pd.concat([mdd,health])\n",
    "    data=data.reset_index(drop =True)\n",
    "    y=data['target']\n",
    "    X=data.drop(columns=['fn', 'target'])\n",
    "    build_models_pca(X,y)\n",
    "    print(\"_______________\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "3b5dbe5d",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "bands.csv\n",
      "fs_lr_l1 0.753+/-0.150\n",
      "fs_lr_l2 0.740+/-0.113\n",
      "fs_rf_7 0.720+/-0.113\n",
      "fs_rf_5 0.739+/-0.116\n",
      "fs_svm_stand 0.778+/-0.113\n",
      "fs_knn 0.663+/-0.116\n",
      "fs_gb 0.685+/-0.136\n",
      "_______________\n",
      "env_theta.csv\n",
      "fs_lr_l1 nan+/-nan\n",
      "fs_lr_l2 nan+/-nan\n",
      "fs_rf_7 nan+/-nan\n",
      "fs_rf_5 nan+/-nan\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "fs_svm_stand nan+/-nan\n",
      "fs_knn nan+/-nan\n",
      "fs_gb nan+/-nan\n",
      "_______________\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/joblib/memory.py\", line 349, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\", line 702, in fit_transform\n",
      "    return self.fit(X, y, **fit_params).transform(X)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 353, in fit\n",
      "    score_func_ret = self.score_func(X, y)\n",
      "  File \"/Users/zubrikhina/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py\", line 218, in chi2\n",
      "    raise ValueError(\"Input X must be non-negative.\")\n",
      "ValueError: Input X must be non-negative.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n"
     ]
    }
   ],
   "source": [
    "for path in Path(DATA_PATH).iterdir():\n",
    "    print(path.name)\n",
    "    data =pd.read_csv(path)\n",
    "    data =data.fillna(0)\n",
    "    y=data['target']\n",
    "    X=data.drop(columns=['fn', 'target'])\n",
    "    build_models_feature_selection(X,y)\n",
    "    print(\"_______________\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e67c1e4c",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
